matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: windows
      language: node_js
      node_js: "10"

    - os: linux
      services: docker
      language: generic
      node_js: "10"

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install yarn;
    fi

script:
  - yarn run lint
  - yarn run test
  - yarn run test:e2e

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
