version: "3"
services:
  prysm-beacon-chain:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    container_name: "cg_prysm_beacon_chain"
    command: --datadir=/data --custom-genesis-delay=0 --bootstrap-node= --deposit-contract 0x4689a3C63CE249355C8a573B5974db21D2d1b8Ef --interop-num-validators 8 --interop-eth1data-votes
    ports:
     - "4000:4000"
     - "13000:13000"
  prysm-validator:
    image: gcr.io/prysmaticlabs/prysm/validator:latest
    container_name: "cg_prysm_validator"
    command: --keymanager=interop --keymanageropts='{"keys":8}' --beacon-rpc-provider prysm-beacon-chain:4000
    restart: on-failure
    depends_on:
      - prysm-beacon-chain
